### ISSUE TITLE
RFC: Authorization

### ISSUE THREAD

**Issue by mxstbr** [StellateHQ/fuse.js#12]
## Summary

We are considering adding authorization as a first-class citizen to Fuse.js.

## Proposed Solution

None yet. It's unclear whether there is a good use case for this, as the common scenario will be that the underlying microservices & third-party APIs already have to handle authentication & authorization.

However, in my personal experience, handling authorization at the GraphQL level (in my case simply through making sure that each resolver has an authorization check) was terrific to work with and kept our system well secure enough. We could e.g. require each `node` to have an `authorize` check that explicitly has to mark things as public via `authorize: () => true` so that it's explicitly note. 

_Note: Pothos has two related plugins: [Authz](https://pothos-graphql.dev/docs/plugins/authz) & [Scope Auth](https://pothos-graphql.dev/docs/plugins/scope-auth)._

**Comment by b-barry** [comment]
I like the authorize function but how do you plan to handle field level authorization?

**Comment by JoviDeCroock** [comment]
Coming back to this, I think I personally prefer us using the [`pothos` auth-scopes plugin](https://pothos-graphql.dev/docs/plugins/scope-auth) as that allows us to have a convenient battle-tested way (we use this at stellate!) of defining authorization on a by-field, by-type, ... level.

The issue we'll face here is the typings aspect as we did fork the `SchemaBuilder` creation to introduce our own opinions. Maybe we can override it through global-types, this is to-test.
