### ISSUE TITLE
Bug: Running `next dev` with the `-p` flag other than 3000 fails

### ISSUE THREAD

**Issue by cstrnt** [StellateHQ/fuse.js#84]
## Description
The `next dev` script has the option to run the dev server using another port than the default one (3000).  Running `next dev -p 3005` will cause fuse to fail

## Versions

- TypeScript Version: 4.9.5
- Fuse version: 0.8.0

**Comment by JoviDeCroock** [comment]
Hey,

You can pass in the port to the plugin, I'll get onto documenting that! Maybe next even exposes that to the plugin, would be a neat addition!

Am I understanding correctly that it's just the codegen not working?

**Comment by JoviDeCroock** [comment]
Going to close this as we haven't heard back, the docs PR was meant to close this either way. As always, if anything pops up feel free to create an issue 🙌
