### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by danstarns** [StellateHQ/fuse.js#95]
We cannot trust this or recommend it to our clients when there is only 1 test file

<img width="594" alt="Screenshot 2023-12-16 at 12 35 27" src="https://github.com/StellateHQ/fuse.js/assets/35999252/69e7fda3-9341-4ec8-929c-741afd000801">

<img width="928" alt="Screenshot 2023-12-16 at 12 38 46" src="https://github.com/StellateHQ/fuse.js/assets/35999252/6a99ed24-f9e3-466f-a137-7aa075898980">

Please add more testing so we can trust this framework and or reach out for help ✌️

**Comment by JoviDeCroock** [comment]
Hey,

I get that that's an issue and I've mainly focussed on integrating with Next.JS which makes it a really big pain to test 😅 

Now that we have #79 merged it becomes an awful lot easier to test things. That being said I would highly encourage "be the change you want to see", feel free to add any tests you like. I'd happily guide folks in that process.

**Comment by danstarns** [comment]
@JoviDeCroock this already looks a lot better and adds more trust to the tool! Thanks.

**Comment by danstarns** [comment]
> Hey,
> 
> I get that that's an issue and I've mainly focussed on integrating with Next.JS which makes it a really big pain to test 😅
> 
> Now that we have #79 merged it becomes an awful lot easier to test things. That being said I would highly encourage "be the change you want to see", feel free to add any tests you like. I'd happily guide folks in that process.
> 
> To be clear this is 100% a missing piece in the repo and the hard testability is no excuse in terms of us having to iterate on this.
> 
> I've added some more general builder tests in #96 however the next part of it would be `fixtures/` where we do the whole `fuse dev --server` and `fuse build --server` workflow and check whether the correct plugins are initialised.

To test compatibility with Next.js wdyt about leveraging a headless browser environment, spawing a Next.js app, building a fuse schema, and then querying it inside the environment asserting the result?
